import pyautogui

pyautogui.hotkey('win','down')
pyautogui.click(554,279 )

pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')                   
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.typewrite('dshalfkhdskjahfkhs')
pyautogui.press('tab')
pyautogui.press('tab')

pyautogui.typewrite('dshalfkhdskjahfkhs')






