test = int(input('enter value of test: '))

all_questions=[]
if test == 5:
    all_questions.append(question.question_no_1)
    all_questions.append(question.question_no_2)
    all_questions.append(question.question_no_3)
    all_questions.append(question.question_no_4)
    all_questions.append(question.question_no_5)

if test == 10:
    all_questions.append(question.question_no_1)
    all_questions.append(question.question_no_2)
    all_questions.append(question.question_no_3)
    all_questions.append(question.question_no_4)
    all_questions.append(question.question_no_5)
    all_questions.append(question.question_no_6)
    all_questions.append(question.question_no_7)
    all_questions.append(question.question_no_8)
    all_questions.append(question.question_no_9)
    all_questions.append(question.question_no_10)

if test == 15:
    all_questions.append(question.question_no_1)
    all_questions.append(question.question_no_2)
    all_questions.append(question.question_no_3)
    all_questions.append(question.question_no_4)
    all_questions.append(question.question_no_5)
    all_questions.append(question.question_no_6)
    all_questions.append(question.question_no_7)
    all_questions.append(question.question_no_8)
    all_questions.append(question.question_no_9)
    all_questions.append(question.question_no_10)
    all_questions.append(question.question_no_11)
    all_questions.append(question.question_no_12)
    all_questions.append(question.question_no_13)
    all_questions.append(question.question_no_14)
    all_questions.append(question.question_no_15)

if test == 20:
    all_questions.append(question.question_no_1)
    all_questions.append(question.question_no_2)
    all_questions.append(question.question_no_3)
    all_questions.append(question.question_no_4)
    all_questions.append(question.question_no_5)
    all_questions.append(question.question_no_6)
    all_questions.append(question.question_no_7)
    all_questions.append(question.question_no_8)
    all_questions.append(question.question_no_9)
    all_questions.append(question.question_no_10)
    all_questions.append(question.question_no_11)
    all_questions.append(question.question_no_12)
    all_questions.append(question.question_no_13)
    all_questions.append(question.question_no_14)
    all_questions.append(question.question_no_15)
    all_questions.append(question.question_no_16)
    all_questions.append(question.question_no_17)
    all_questions.append(question.question_no_18)
    all_questions.append(question.question_no_19)
    all_questions.append(question.question_no_20)

if test == 25:
    all_questions.append(question.question_no_1)
    all_questions.append(question.question_no_2)
    all_questions.append(question.question_no_3)
    all_questions.append(question.question_no_4)
    all_questions.append(question.question_no_5)
    all_questions.append(question.question_no_6)
    all_questions.append(question.question_no_7)
    all_questions.append(question.question_no_8)
    all_questions.append(question.question_no_9)
    all_questions.append(question.question_no_10)
    all_questions.append(question.question_no_11)
    all_questions.append(question.question_no_12)
    all_questions.append(question.question_no_13)
    all_questions.append(question.question_no_14)
    all_questions.append(question.question_no_15)
    all_questions.append(question.question_no_16)
    all_questions.append(question.question_no_17)
    all_questions.append(question.question_no_18)
    all_questions.append(question.question_no_19)
    all_questions.append(question.question_no_20)
    all_questions.append(question.question_no_21)
    all_questions.append(question.question_no_22)
    all_questions.append(question.question_no_23)
    all_questions.append(question.question_no_24)
    all_questions.append(question.question_no_25)




